version: '3.8'

services:
  # 前端应用
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lingce_ltest_frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - lingce_ltest_network

networks:
  lingce_ltest_network:
    driver: bridge
