# Generated by Django 4.2.7 on 2026-09-30 03:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=32, unique=True, verbose_name='缺陷编号')),
                ('title', models.CharField(max_length=300, verbose_name='缺陷标题')),
                ('description', models.TextField(blank=True, verbose_name='缺陷描述')),
                ('reproduce_steps', models.TextField(blank=True, verbose_name='复现步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('module', models.CharField(blank=True, max_length=120, verbose_name='所属模块')),
                ('severity', models.CharField(choices=[('blocker', '阻塞'), ('critical', '严重'), ('major', '一般'), ('minor', '轻微'), ('suggestion', '建议')], default='major', max_length=20, verbose_name='严重级别')),
                ('priority', models.CharField(choices=[('p0', 'P0'), ('p1', 'P1'), ('p2', 'P2'), ('p3', 'P3')], default='p2', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('new', '新建'), ('assigned', '已指派'), ('in_progress', '修复中'), ('resolved', '待回归'), ('verified', '回归通过'), ('rejected', '已驳回'), ('reopened', '重新打开'), ('closed', '已关闭')], default='new', max_length=30, verbose_name='状态')),
                ('defect_type', models.CharField(choices=[('functional', '功能缺陷'), ('ui', '界面缺陷'), ('compatibility', '兼容性缺陷'), ('performance', '性能缺陷'), ('security', '安全缺陷'), ('data', '数据缺陷'), ('other', '其他')], default='functional', max_length=30, verbose_name='缺陷类型')),
                ('source', models.CharField(choices=[('manual', '手工测试'), ('api_testing', 'API测试'), ('ui_automation', 'UI自动化'), ('app_automation', 'APP自动化'), ('production', '生产反馈')], default='manual', max_length=30, verbose_name='来源')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='期望修复时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Bug缺陷',
                'verbose_name_plural': 'Bug缺陷',
                'db_table': 'defects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='附件名称')),
                ('file', models.FileField(upload_to='defect_attachments/', verbose_name='附件文件')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '缺陷附件',
                'verbose_name_plural': '缺陷附件',
                'db_table': 'defect_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '缺陷评论',
                'verbose_name_plural': '缺陷评论',
                'db_table': 'defect_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DefectTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='原状态')),
                ('to_status', models.CharField(max_length=30, verbose_name='目标状态')),
                ('comment', models.TextField(blank=True, verbose_name='流转说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='defects.defect', verbose_name='缺陷')),
            ],
            options={
                'verbose_name': '缺陷流转记录',
                'verbose_name_plural': '缺陷流转记录',
                'db_table': 'defect_transitions',
                'ordering': ['-created_at'],
            },
        ),
    ]
