# Generated by Django 4.2.7 on 2026-09-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='用于标识该通知配置的名称', max_length=100, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('webhook_feishu', '飞书机器人'), ('webhook_wechat', '企业微信机器人'), ('webhook_dingtalk', '钉钉机器人'), ('email', '邮箱通知')], default='webhook_feishu', max_length=20, verbose_name='配置类型')),
                ('webhook_bots', models.JSONField(blank=True, default=dict, help_text='飞书、企微、钉钉机器人配置', null=True, verbose_name='Webhook机器人配置')),
                ('email_smtp_host', models.CharField(blank=True, default='', help_text='如 smtp.qq.com', max_length=200, verbose_name='SMTP服务器')),
                ('email_smtp_port', models.IntegerField(default=465, verbose_name='SMTP端口')),
                ('email_use_ssl', models.BooleanField(default=True, help_text='端口465选SSL，端口587选TLS', verbose_name='使用SSL')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='使用TLS')),
                ('email_host_user', models.CharField(blank=True, default='', max_length=200, verbose_name='发件邮箱账号')),
                ('email_host_password', models.CharField(blank=True, default='', help_text='不是登录密码，是邮箱开启SMTP后生成的授权码', max_length=200, verbose_name='邮箱授权码')),
                ('email_from', models.CharField(blank=True, default='', help_text='通常与发件邮箱账号相同', max_length=200, verbose_name='发件人地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认配置')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '统一通知配置',
                'verbose_name_plural': '统一通知配置',
                'db_table': 'unified_notification_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
