# Generated by Django 4.2.7 on 2026-09-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='default_post_action',
        ),
        migrations.RemoveField(
            model_name='testsuitetestcase',
            name='post_action',
        ),
    ]
