# Generated by Django 4.2.7 on 2026-07-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0004_login_config_refactor_to_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='action_type',
            field=models.CharField(choices=[('click', '点击'), ('fill', '输入文本'), ('select', '选择下拉选项'), ('getText', '获取文本'), ('waitFor', '等待元素'), ('hover', '悬停'), ('scroll', '滚动'), ('screenshot', '截图'), ('assert', '断言'), ('wait', '等待'), ('switchTab', '切换标签页'), ('navigate', '路由跳转')], max_length=20, verbose_name='操作类型'),
        ),
    ]
