# Generated by Django 4.2.7 on 2026-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0005_add_select_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasestep',
            name='assert_type',
            field=models.CharField(blank=True, choices=[('textContains', '文本包含'), ('textEquals', '文本等于'), ('isVisible', '元素可见'), ('exists', '元素存在'), ('hasAttribute', '属性值'), ('tableContains', '表格包含文本'), ('tableEmpty', '表格为空')], max_length=20, verbose_name='断言类型'),
        ),
    ]
