# Generated by Django 4.2.7 on 2026-07-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0008_change_parent_group_on_delete_to_set_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasestep',
            name='action_wait',
            field=models.IntegerField(default=0, help_text='步骤操作成功后等待指定秒数再执行下一步，用于等待动画/加载完成', verbose_name='操作后等待(秒)'),
        ),
    ]
