# Generated by Django 4.2.7 on 2026-07-17 02:09

from django.db import migrations, models


def update_existing_status(apps, schema_editor):
    """将已有的 draft/ready/running 状态更新为 normal"""
    TestCase = apps.get_model('ui_automation', 'TestCase')
    TestCase.objects.filter(status__in=['draft', 'ready', 'running']).update(status='normal')


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0017_alter_testcase_options_testcase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('passed', '通过'), ('failed', '失败')], default='normal', max_length=20, verbose_name='状态'),
        ),
        migrations.RunPython(update_existing_status, migrations.RunPython.noop),
    ]
