# Generated by Django 4.2.7 on 2026-07-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0019_add_precondition_sql'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('normal', '正常'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过')], default='normal', max_length=20, verbose_name='状态'),
        ),
    ]
