# Generated by Django 4.2.7 on 2026-07-29 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0023_change_base_url_to_charfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('status', models.CharField(choices=[('generating', '生成中'), ('completed', '已完成'), ('failed', '生成失败')], default='generating', max_length=20, verbose_name='生成状态')),
                ('report_dir', models.CharField(blank=True, default='', max_length=500, verbose_name='报告目录路径')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总用例数')),
                ('passed_cases', models.IntegerField(default=0, verbose_name='通过用例数')),
                ('failed_cases', models.IntegerField(default=0, verbose_name='失败用例数')),
                ('skipped_cases', models.IntegerField(default=0, verbose_name='跳过用例数')),
                ('pass_rate', models.FloatField(default=0, verbose_name='通过率(%)')),
                ('avg_duration', models.FloatField(default=0, verbose_name='平均执行耗时(秒)')),
                ('browser', models.CharField(blank=True, default='', max_length=50, verbose_name='浏览器')),
                ('environment', models.CharField(blank=True, default='', max_length=100, verbose_name='执行环境')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allure_reports', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allure_reports', to='ui_automation.uiproject', verbose_name='所属项目')),
                ('test_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allure_reports', to='ui_automation.testexecution', verbose_name='执行批次')),
                ('test_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allure_reports', to='ui_automation.uitestplan', verbose_name='测试计划')),
            ],
            options={
                'verbose_name': 'Allure测试报告',
                'verbose_name_plural': 'Allure测试报告',
                'db_table': 'ui_allure_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
