# Generated by Django 4.2.7 on 2026-08-01 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0027_add_midscene_advanced_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='项目描述')),
                ('status', models.CharField(choices=[('NOT_STARTED', '未开始'), ('IN_PROGRESS', '进行中'), ('COMPLETED', '已结束')], default='IN_PROGRESS', max_length=20, verbose_name='项目状态')),
                ('default_platform', models.CharField(choices=[('web', 'Web端'), ('app', 'APP端')], default='web', max_length=10, verbose_name='默认平台')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('members', models.ManyToManyField(blank=True, related_name='ai_projects', to=settings.AUTH_USER_MODEL, verbose_name='团队成员')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ai_projects', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': 'AI自动化项目',
                'verbose_name_plural': 'AI自动化项目',
                'db_table': 'ai_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='midscenecase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midscene_cases', to='ui_automation.aiproject', verbose_name='所属项目'),
        ),
        migrations.AlterField(
            model_name='midscenegroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midscene_groups', to='ui_automation.aiproject', verbose_name='所属项目'),
        ),
    ]
