# Generated by Django 4.2.7 on 2026-08-01 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0028_aiproject_alter_midscenecase_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('task_type', models.CharField(choices=[('MIDSCENE_CASE', 'Midscene用例执行')], default='MIDSCENE_CASE', max_length=20, verbose_name='任务类型')),
                ('trigger_type', models.CharField(choices=[('CRON', 'Cron表达式'), ('INTERVAL', '固定间隔'), ('ONCE', '单次执行')], max_length=20, verbose_name='触发器类型')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron表达式')),
                ('interval_seconds', models.IntegerField(blank=True, null=True, verbose_name='间隔秒数')),
                ('execute_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('notify_on_success', models.BooleanField(default=False, verbose_name='成功时通知')),
                ('notify_on_failure', models.BooleanField(default=False, verbose_name='失败时通知')),
                ('notification_type', models.CharField(blank=True, choices=[('email', '邮箱通知'), ('webhook', 'Webhook机器人'), ('both', '两者都发送')], max_length=20, verbose_name='通知类型')),
                ('notify_emails', models.JSONField(blank=True, default=list, verbose_name='通知邮箱列表')),
                ('status', models.CharField(choices=[('ACTIVE', '激活'), ('PAUSED', '暂停'), ('COMPLETED', '已完成'), ('FAILED', '失败')], default='ACTIVE', max_length=20, verbose_name='任务状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('total_runs', models.IntegerField(default=0, verbose_name='总运行次数')),
                ('successful_runs', models.IntegerField(default=0, verbose_name='成功运行次数')),
                ('failed_runs', models.IntegerField(default=0, verbose_name='失败运行次数')),
                ('last_result', models.JSONField(default=dict, verbose_name='最后执行结果')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('midscene_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.midscenecase', verbose_name='Midscene用例')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui_automation.aiproject', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': 'AI定时任务',
                'verbose_name_plural': 'AI定时任务',
                'db_table': 'ai_scheduled_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
