# Generated by Django 4.2.7 on 2026-08-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0029_ai_scheduled_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiNotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='任务名称')),
                ('task_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='任务类型快照')),
                ('notification_type', models.CharField(choices=[('task_execution', '定时任务执行'), ('case_execution', '用例执行'), ('system_alert', '系统警告')], max_length=50, verbose_name='通知类型')),
                ('sender_name', models.CharField(max_length=100, verbose_name='发件人姓名')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='发件人邮箱')),
                ('recipient_info', models.JSONField(verbose_name='收件人信息')),
                ('webhook_bot_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='Webhook机器人信息')),
                ('notification_content', models.TextField(verbose_name='通知内容')),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sending', '发送中'), ('success', '发送成功'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('response_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='响应信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('is_retried', models.BooleanField(default=False, verbose_name='是否已重试')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ui_automation.aischeduledtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': 'AI通知日志',
                'verbose_name_plural': 'AI通知日志',
                'db_table': 'ai_notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ai_notifica_status_d619be_idx'), models.Index(fields=['notification_type'], name='ai_notifica_notific_efdf99_idx'), models.Index(fields=['created_at'], name='ai_notifica_created_58cc41_idx')],
            },
        ),
    ]
