# Generated by Django 4.2.7 on 2026-08-01 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui_automation', '0030_ai_notification_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='计划名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='计划描述')),
                ('platform', models.CharField(choices=[('web', 'Web端'), ('app', 'APP端')], default='web', max_length=10, verbose_name='平台')),
                ('execution_status', models.CharField(choices=[('not_run', '未执行'), ('passed', '通过'), ('failed', '失败'), ('running', '执行中')], default='not_run', max_length=20, verbose_name='执行状态')),
                ('total_cases', models.IntegerField(default=0, verbose_name='用例总数')),
                ('passed_count', models.IntegerField(default=0, verbose_name='通过数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('skipped_count', models.IntegerField(default=0, verbose_name='跳过数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_test_plans', to='ui_automation.aiproject', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': 'AI测试计划',
                'verbose_name_plural': 'AI测试计划',
                'db_table': 'ai_test_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiTestPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('midscene_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ui_automation.midscenecase', verbose_name='Midscene用例')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_items', to='ui_automation.aitestplan', verbose_name='所属计划')),
            ],
            options={
                'verbose_name': 'AI测试计划项',
                'verbose_name_plural': 'AI测试计划项',
                'db_table': 'ai_test_plan_items',
                'ordering': ['order'],
            },
        ),
    ]
