# Generated by Django 4.2.7 on 2026-08-03 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_automation', '0038_ai_test_plan_add_execution_mode_login_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='midscenegroup',
            name='platform',
            field=models.CharField(choices=[('web', 'Web端'), ('app', 'APP端')], default='web', max_length=10, verbose_name='平台'),
        ),
    ]
